### PR TITLE
EXT-732: Update ExtGen to support Ext JS 6.7

### PR DESCRIPTION
**Pull request by dalley**
Fix for https://sencha.jira.com/browse/EXT-732

### CODE REVIEW

**Comment by dalley** [comment]
@jnsencha please review

**Comment by dalley** [comment]
@mgusmano please review.

**Comment by jnsencha** [comment]
@dalley please merge 6.7 work into the 6.7 branch

**Comment by mgusmano** [comment]
has this been merged into 6.7.x branch?

**Pull request merged**
